### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object

### ISSUE THREAD

**Issue by adi-miller** [ngnijland/MMM-social-counter#3]
[16:35:49.948] [ERROR]  TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at request (https.js:272:10)
    at Object.get (https.js:276:15)
    at Class.twitterGetFollowers (/home/pi/MagicMirror/modules/MMM-social-counter/node_helper.js:87:8)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-social-counter/node_helper.js:17:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by adi-miller** [comment]
This seems to be caused by a conflicting dependency I have from other modules... I guess. Fixed by changing it from .get to .request:
```
  twitterGetFollowers: function (username) {
		var options = {
			hostname: 'api.twitter.com',
			port: 443,
			path: '/1.1/users/show.json?screen_name=${username}',
			method: 'GET',
			headers: {
				Authorization: `Bearer ${this.jwt}`,
			},
		};
    https.request(options,
        (res) => {

```
But now I seem to get "socket hang up"...

**Comment by ngnijland** [comment]
Hi @adi-miller 

Thanks for taking the time to submit an issue!

Are you by any chance using a node version earlier than `10.9.0`? I think the `https.get` method accepts only two arguments instead of three (the way I use it). I'll create a pull request where I use the older api as I think it is still supported in newer node versions!

Regards,
Niek

**Comment by ngnijland** [comment]
@adi-miller can you check if the error also occurs when using the following branch: `fix/https-get-older-nodejs`? If the error is gone I'll merge the PR into master!

Thanks in advance!

**Comment by adi-miller** [comment]
I'm using:
```
pi@mm2:~ $ node -v
v14.10.1
```
But yes, that solved the problem. Thanks!

**Comment by ngnijland** [comment]
Oh weird, the api changed again in a newer version than apparently. Glad I could help! I'll merge it into master
